### ISSUE TITLE
Really interesting

### ISSUE THREAD

**Issue by otoolep** [mmaul/cl-influxdb#4]
Just want to say this seems really interesting -- I've been looking at Lisp, so I'll be studying this since I know InfluxDB pretty well.

**Comment by mmaul** [comment]
otoolep,
Thanks,I might want to pick your brain on the influxdb side, I'm developing
a network protocol analyzer in lisp that is backed by a Influxdb datastore.
There are some things arcitecture-wise on the influxdb side that I'm not
sure about. If you have any suggestion or improvements feel free to open an
issue or send a pull request or email me directly.

**Comment by otoolep** [comment]
Sure, happy to help.

Bear in mind I know close to nothing about Lisp -- I would just like to follow Eric Raymond's advice that knowing it would make me better code. 

Feel free to drop me a line anytime at: philip at influxdb ....
