### ISSUE TITLE
still active?

### ISSUE THREAD

**Issue by beckettsean** [mmaul/cl-influxdb#5]
I'm cleaning up the https://docs.influxdata.com/influxdb/v1.0/tools/api_client_libraries/ page and removing those libraries that aren't compatible with InfluxDB 1.0. 

I'll remove this project from that page on October 15th unless you have plans to update for 1.0 compatibility. Thanks!

**Comment by mmaul** [comment]
Yea, actually will have 1.0 compatibility next week

**Comment by beckettsean** [comment]
Awesome news, thanks, @mmaul! We will leave the library on our API page.

When you get that checked in, drop a note to contact@influxdb.com and tell them I said to send you a t-shirt and some stickers, thanks!

**Comment by mmaul** [comment]
Verified support w/version 1.0. One thing though could you add SSL set up instructions to the docs for openssl key/cert generation for SSL support in influxdb. I'm getting 'failed to parse private key'
